IsRecord: false

control_configuration:

  kp: [30 , 30 , 30 , 30 , 3 , 30 , 30 , 30 , 30 , 3]
  kd: [4  , 4  , 4  , 4  , 1 , 4  , 4  , 4  , 4  , 1]

  #kp: [0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0]
  #kd: [0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0]
