planner_name: velocity_reversal_lipm
swing_height: 0.12
push_down_height: 0.0
default_target_foot_location: [0.0, 0.11, 0.0]

#kp: [ 150 , 150 , 200 , 200 , 5 , 150 , 150 , 150 , 150 , 5 ]
#kd: [ 8   , 8   , 10   , 10   , 0 , 8   , 8   , 8   , 8   , 0 ]

kp: [100 , 100 , 100 , 100 , 5 , 100 , 100 , 100 , 100 , 5 ]
kd: [4   , 4   , 4   , 4   , 0 , 4   , 4   , 4   , 4   , 0  ]

body_pt_offset: [-0.07, -0.005]
foot_landing_offset: [0., 0.]
