planner_name: velocity_reversal_lipm
swing_height: 0.12
push_down_height: 0.0
default_target_foot_location: [-0.03, 0.11, 0.0]

#kp: [ 150 , 150 , 200 , 200 , 5 , 150 , 150 , 150 , 150 , 5 ]
#kd: [ 8   , 8   , 10   , 10   , 0 , 8   , 8   , 8   , 8   , 0 ]

kp: [100 , 250 , 250 , 200 , 5 , 100 , 150 , 150 , 150 , 5 ]
kd: [4   , 8   , 8   , 8   , 0 , 4   , 6   , 6   , 6   , 0  ]

body_pt_offset: [-0.05, 0.0]
foot_landing_offset: [0., 0.]

fin_ankle: 1.3
