###### Normal Gain

#jp_kp         : [80 , 100 , 100 , 100 , 18  , 80 , 100 , 100 , 100 , 18]
#jp_kd         : [5  , 8   , 8   , 8   , 1.5 , 5  , 8   , 8   , 8   , 1.5]
#t_kp          : [0  , 0   , 0   , 0   , 0   , 0  , 0   , 0   , 0   , 0]
#t_kd          : [0  , 0   , 0   , 0   , 0   , 0  , 0   , 0   , 0   , 0]
#en_auto_kd    : [1  , 1   , 1   , 1   , 1   , 1  , 1   , 1   , 1   , 1]
#en_dob        : [0  , 0   , 0   , 0   , 0   , 0  , 0   , 0   , 0   , 0]
#current_limit : [5 , 10  , 10  , 10  , 3  , 5 , 10  , 10  , 10  , 3]

####### Weak Gain

jp_kp             : [30  , 70  , 70  , 70  , 9   , 30  , 70  , 70  , 70  , 9]
jp_kd             : [2   , 4   , 4   , 4   , 0.4 , 2   , 4   , 4   , 4   , 0.4]
t_kp              : [0   , 0   , 0   , 0   , 0   , 0   , 0   , 0   , 0   , 0]
t_kd              : [0   , 0   , 0   , 0   , 0   , 0   , 0   , 0   , 0   , 0]
en_auto_kd        : [1   , 1   , 1   , 1   , 1   , 1   , 1   , 1   , 1   , 1]
en_dob            : [0   , 0   , 0   , 0   , 0   , 0   , 0   , 0   , 0   , 0]
current_limit     : [5   , 7   , 19  , 22  , 5   , 5   , 7   , 19  , 22  , 5]
temperature_limit : [110 , 110 , 110 , 110 , 110 , 110 , 110 , 110 , 110 , 110]
