service_call:
    jp_kp             : [0.  , 0.   , 0.   , 0.   , 0.  , 0.  , 0.   , 0.   , 0.   , 0.]
    jp_kd             : [0.  , 0.   , 0.   , 0.   , 0.  , 0.  , 0.   , 0.   , 0.   , 0.]
    t_kp              : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
    t_kd              : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
    en_auto_kd        : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
    en_dob            : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
    rotor_inertia     : [20. , 120. , 120. , 510. , 20. , 20. , 120. , 120. , 510. , 20.]
    temperature_limit : [110 , 110  , 110  , 110  , 110 , 110 , 110  , 110  , 110  , 350]
    current_limit     : [8   , 20   , 19   , 22   , 15  , 8   , 20   , 19   , 22   , 15]

#service_call:
    #jp_kp             : [20  , 20   , 20   , 20   , 10  , 20  , 20   , 20   , 20   , 10.]
    #jp_kd             : [4   , 4    , 4    , 4    , 2.  , 4   , 4    , 4    , 4    , 2.]
    #t_kp              : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
    #t_kd              : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
    #en_auto_kd        : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
    #en_dob            : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
    #rotor_inertia     : [20. , 120. , 120. , 510. , 20. , 20. , 120. , 120. , 510. , 20.]
    #temperature_limit : [110 , 110  , 110  , 110  , 110 , 110 , 110  , 110  , 110  , 350]
    #current_limit     : [8   , 20   , 19   , 22   , 15  , 8   , 20   , 19   , 22   , 15]

#service_call:
    #jp_kp             : [50  , 95   , 95   , 95   , 10  , 50  , 95   , 95   , 95   ,  10.]
    #jp_kd             : [5  ,  8   ,  8   ,  8   ,  2.  ,  5  ,  8   ,  8   ,  8   ,  2.]
    #t_kp              : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
    #t_kd              : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
    #en_auto_kd        : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
    #en_dob            : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
    #rotor_inertia     : [20. , 120. , 120. , 510. , 20. , 20. , 120. , 120. , 510. , 20.]
    #temperature_limit : [110 , 110  , 110  , 110  , 110 , 110 , 110  , 110  , 110  , 350]
    #current_limit     : [8   , 20   , 19   , 22   , 15   , 8   , 20   , 19   , 22   , 15]

safety_turn_off:
    min_position    : [-0.6 , -0.4 , -1.15 , -0.2 , 0.64 , -0.6 , -0.4 , -1.15 , -0.2 , 0.64]
    max_position    : [0.6  , 0.4  , 0.5   , 1.9  , 2.33 , 0.6  , 0.4  , 0.5   , 1.9  , 2.33]
    max_velocity    : [10.  , 10.  , 10.   , 10.  , 10.  , 10.  , 10.  , 10.   , 10.  , 10.]
    max_trq         : [200. , 200. , 200.  , 200. , 100.  , 200. , 200. , 200.  , 200. , 100.]
    max_temperature : [100. , 100. , 100.  , 100. , 350. , 100. , 100. , 100.  , 100. , 350.]
