###### Normal Gain

#jp_kp         : [80 , 100 , 100 , 100 , 18  , 80 , 100 , 100 , 100 , 18]
#jp_kd         : [5  , 8   , 8   , 8   , 1.5 , 5  , 8   , 8   , 8   , 1.5]
#t_kp          : [0  , 0   , 0   , 0   , 0   , 0  , 0   , 0   , 0   , 0]
#t_kd          : [0  , 0   , 0   , 0   , 0   , 0  , 0   , 0   , 0   , 0]
#en_auto_kd    : [1  , 1   , 1   , 1   , 1   , 1  , 1   , 1   , 1   , 1]
#en_dob        : [0  , 0   , 0   , 0   , 0   , 0  , 0   , 0   , 0   , 0]
#current_limit : [5 , 10  , 10  , 10  , 3  , 5 , 10  , 10  , 10  , 3]

####### Weak Gain

jp_kp             : [30  , 80   , 80   , 80   , 5   , 30  , 80   , 80   , 80   , 5]
jp_kd             : [2   , 5    , 5    , 5    , 1   , 2   , 5    , 5    , 5    , 1]
t_kp              : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
t_kd              : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
en_auto_kd        : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
en_dob            : [0   , 0    , 0    , 0    , 0   , 0   , 0    , 0    , 0    , 0]
rotor_inertia     : [20. , 105. , 105. , 420. , 20. , 20. , 105. , 105. , 420. , 20.]
temperature_limit : [110 , 110  , 110  , 110  , 110 , 110 , 110  , 110  , 110  , 110]
current_limit     : [8   , 20   , 19   , 22   , 3   , 8   , 20   , 19   , 22   , 3]

#contact_thresold
