is_record: false

#hanging_height: 0.81
hanging_height: 0.83

release_time: 8
#release_time: 0

initial_configuration: [0, 0, -0.5, 1.8, 1.03, 0, 0, -0.5, 1.8, 1.03]

control_configuration:

  kp: [30 , 50 , 70 , 70 , 10 , 30 , 50 , 70 , 70 , 10]
  kd: [3  , 5  , 7  , 7  , 1  , 3  , 5  , 7  , 7  , 1]

  #kp: [0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0]
  #kd: [0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0]
