is_record: false

control_configuration:

  kp: [100 , 100 , 100 , 100 , 50 , 100 , 100 , 100 , 100 , 50]
  kd: [5   , 5   , 5   , 5   , 2  , 5   , 5   , 5   , 5   , 2]
  #kp: [0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0]
  #kd: [0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0]
