is_record: false
servo_rate: 0.001 # !!this should be match with controller servo rate!!
num_steps_per_cycle: 30
hanging_height: 0.83
display_joint_frame: false
display_target_frame: true
joint_limit_enforced: true
initial_configuration: [0, 0, -0.5, 1.8, 1.03, 0, 0, -0.5, 1.8, 1.03]

plot_target: true
plot_adjusted_foot: true
plot_guided_foot: true
camera_manipulator: false
print_computation_time: false
#release_time: 4.20
release_time: 0.5

### Toggle for RL ###
show_viewer: true
#show_viewer: false
check_collision: true
#check_collision: false


control_configuration:
  kp: [100 , 100 , 100 , 100 , 10 , 100 , 100 , 100 , 100 , 10]
  kd: [20  , 20  , 20  , 20  , 1  , 20  , 20  , 20  , 20  , 1]
