is_record: false

hanging_height: 0.8

release_time: 70

initial_configuration: [0, 0, -0.5, 1.8, 1.03, 0, 0, -0.5, 1.8, 1.03]

control_configuration:

  kp: [50 , 70 , 70 , 70 , 30 , 50 , 70 , 70 , 70 , 30]
  kd: [5  , 5  , 5  , 5  , 2  , 5  , 5  , 5  , 5  , 2]

  #kp: [0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0]
  #kd: [0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0]
