is_record: false
servo_rate: 0.001 # !!this should be match with controller servo rate!!
num_steps_per_cycle: 30
hanging_height: 0.8729 #0.83
display_joint_frame: false
display_target_frame: true
joint_limit_enforced: true
#initial_configuration: [0, 0, -0.5, 1.8, 1.03, 0, 0, -0.5, 1.8, 1.03]
# initial_configuration: [0., 0., -0.8, 1.6, 0.81, 0., 0, -0.8, 1.6, 0.81]
initial_configuration: [0., 0., -0.785, 1.3565, 1.0, 0., 0, -0.785, 1.3565, 1.0]


plot_adjusted_foot: false
plot_guided_foot: false
camera_manipulator: false
print_computation_time: false
# release_time: 0.50
#release_time: 6.20
release_time: 4.0
# release_time: 100   

### Toggle for RL ###
show_viewer: true
#show_viewer: false
# check_collision: true
check_collision: false


control_configuration:
  # For admittance control:
  # kp: [1000 , 1000 , 1000 , 1000 , 1000 , 1000 , 1000 , 1000 , 1000 , 1000]
  # kd: [20  , 20  , 20  , 20  , 20  , 20  , 20  , 20  , 20  , 20]
  
  # Combined:
  kp: [100 , 100 , 100 , 100 , 100 , 100 , 100 , 100 , 100 , 100]
  kd: [20  , 20  , 20  , 20  , 1  , 20  , 20  , 20  , 20  , 1]
  # kp: [5 , 5 , 5 , 5 , 5 , 5 , 5 , 5 , 5 , 5]
  # kd: [0.1  ,  0.1 ,  0.1 ,  0.1 ,  0.1 ,  0.1 ,  0.1 ,  0.1 ,  0.1  , 0.1]

  # Torque control only
  # kp: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  # kd: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
