is_record: false

hanging_height: 0.95217

release_time: 1000

control_configuration:

  #kp: [30 , 30 , 30 , 30 , 3 , 30 , 30 , 30 , 30 , 3]
  #kd: [3  , 3  , 3  , 3  , 1 , 3  , 3  , 3  , 3  , 1]

  kp: [0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0]
  kd: [0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0]
