InitialState: [0., 3.1415, 0., 0.]
FinalState: [0., 0., 0., 0]
NumTimeSample: 21
MinimumTimeStep: 0.1
MaximumTimeStep: 0.4
StartTime: 0.
EndTime: 100.
TorqueLimit: 40.
InputCost: 10.
TimeSpanInit: 4.
