env:

    # ==========================================================================
    # Observation
    # [cart position, cart velocity, pole position, pole velocity]
    # ==========================================================================
    obs_lower_bound  : [-5 , -10, -0.785, -5]
    obs_upper_bound  : [5  , 10, 0.785, 5]

    # ==========================================================================
    # Action
    # [cart force]
    # ==========================================================================
    action_lower_bound : -10
    action_upper_bound : 10

    # ==========================================================================
    # Terminate condition
    # ==========================================================================

    #terminate_state_lower_bound: []
    #terminate_state_upper_bound: []
