#x_step_length_limit: [-0.6, 0.6]
#y_step_length_limit: [0.15, 0.9]

x_step_length_limit: [-0.4, 0.4]
y_step_length_limit: [0.20, 0.55]

com_velocity_limit: [0.0, 1.3]

#t_prime: [0.22 , 0.22]
#kappa: [-0.16, -0.16]

t_prime: [0.21 , 0.20]
kappa: [-0.08, -0.13]
#kappa: [-0.06, -0.16]
