is_record: false
servo_rate: 0.001 # !!this should be match with controller servo rate!!
#show_viewer: false
show_viewer: true
num_steps_per_cycle: 30
display_joint_frame: true
#display_joint_frame: false
display_target_frame: true
actuator_type: 1 # servo mode 
q_init: [ -90,  0,	-90,	0,	0]

## Camera
from: [5.21, -5.42, 3.5]
to: [1.0, 0.2, 0.5]

## Manipulator
#p1: [-0.3, -0.4, -0.15]
#p2: [-0.3, -0.6, -0.15]
#
#p1: [-0.3, -0.4, -0.20]
#p2: [0.3, 0.4, 0.20]

p1: [-0.3, -0.4, -0.20]
p2: [-0.1, -0.1, 0.1]

#p1: [-0.3, -0.4, -0.01]
#p2: [0.4, -0.90, 0.06]

## Draco
x: -0.9
y: 2.1
th: 1.57
x2: 0.4

## box kp kd
box_kp: [200,200,200,200,200,200]
box_kd: [5,5,5,5,5,5]
draco_top_height: 1.150233
