servo_rate: 0.001

initial_configuration:
    height: 0.90
    yaw: 0

#show_viewer: true
show_viewer: false
show_joint_frame: false
show_target_frame: true
plot_guided_foot: true
plot_adjusted_foot: true
camera_manipulator: false

control_configuration:
    kp: 400
    kd: 10
